[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
title = "SWIM IsaacLab RL"
author = "SWIMLab Project Developers"
maintainer = "SWIMLab Project Developers"
description = "Extension containing reinforcement learning related utilities."
readme = "docs/README.md"
repository = "https://github.com/makolon/SWIMLab"
category = "isaaclab"
keywords = ["extension", "isaalab"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}

[core]
reloadable = false

[[python.module]]
name = "swimlab_rl"
